#!/bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END

#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#

EXEC_ATTR_FILE=/etc/security/exec_attr
EXEC_ATTR="FUSE File System Management:solaris:cmd:::/usr/lib/fs/fuse/fusermount.bin:privs=sys_mount"

egrep -s "$EXEC_ATTR" $EXEC_ATTR_FILE
if [ $? -eq 1 ]; then
	echo $EXEC_ATTR >> $EXEC_ATTR_FILE
fi

PROF_ATTR_FILE=/etc/security/prof_attr
PROF_ATTR="FUSE File System Management:::Mount and unmount FUSE filesystems:"

egrep -s "$PROF_ATTR" $PROF_ATTR_FILE
if [ $? -eq 1 ]; then
	echo $PROF_ATTR >> $PROF_ATTR_FILE
fi

